services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    container_name: logstrap-backend
    networks:
      - config-manager_proxy

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    networks:
      - config-manager_proxy
    restart: always
    container_name: logstrap-frontend
    depends_on:
      - backend
    env_file:
      - .env
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:


networks:
  config-manager_proxy:
    external: true