services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      
    
    ports:
      - 5000:5000
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


volumes:
  postgres_data:
