@url = http://localhost:5000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfancwNnVrNXg0anpubTRqbGl3OGRrZ3F3IiwiaWF0IjoxNzI4MTUwNDcxLCJleHAiOjE3MzA3NDI0NzF9.VOOfRq1zAfcRsF-5lKRtqXbh_ZC4omuf0yfB37KvvT0

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "email":"gillgurpal699@gmail.com",
    "password":"password"
}

###
POST {{url}}/auth/register
Content-Type: application/json

{
    "email":"gillgurpal699@gmail.com",
    "password":"password",
    "name":"Gurpal Singh"
}

###
GET {{url}}/auth/@me
Authorization: Bearer {{token}}

###
GET {{url}}/projects/pj_dc5m03j76kbrku4ahn64ober/keys
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"ok"
}